name: Build .NET

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build solution
        run: dotnet build DHI.Mike1D.Examples/DHI.Mike1D.Examples.sln --configuration Debug

      - name: Run tests
        run: dotnet test DHI.Mike1D.Examples/DHI.Mike1D.Examples.sln --configuration Debug --no-build --verbosity normal

